version = 0.1

[default.deploy.parameters]
stack_name = "ws-serverless-patterns-userprofile"
capabilities = ["CAPABILITY_IAM"]
resolve_s3 = true
confirm_changeset = false

[default.deploy.parameters.parameter_overrides]
UserPool = "us-east-1_5hX9jYpeh"

[default.global.parameters]
region = "us-east-1"
